name: Test Self-Hosted Runner

on:
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [ main ]

jobs:
  test-runner:
    runs-on: self-hosted  # This tells GitHub to use your runner
    
    steps:
    - name: Check runner info
      run: |
        echo "Runner name: $RUNNER_NAME"
        echo "Runner OS: $RUNNER_OS"
        echo "Runner architecture: $RUNNER_ARCH"
        echo "Hostname: $(hostname)"
        echo "Current user: $(whoami)"
        echo "Working directory: $(pwd)"
        
    - name: System information
      run: |
        echo "=== System Info ==="
        uname -a
        echo "=== CPU Info ==="
        cat /proc/cpuinfo | grep "model name" | head -1
        echo "=== Memory Info ==="
        free -h
        echo "=== Disk Info ==="
        df -h
        
    - name: Test basic commands
      run: |
        echo "Testing basic commands..."
        
        # Check git
        if command -v git &> /dev/null; then
          echo "Git is installed: $(git --version)"
        else
          echo "Git is NOT installed"
        fi
        
        # Check curl
        if command -v curl &> /dev/null; then
          echo "Curl is installed: $(curl --version | head -1)"
        else
          echo "Curl is NOT installed"
        fi
        
        # Check docker
        if command -v docker &> /dev/null; then
          echo "Docker is installed: $(docker --version)"
        else
          echo "Docker is NOT installed"
        fi
        
    - name: Simple computation test
      run: |
        echo "Testing computation..."
        for i in {1..5}; do
          echo "Iteration $i: $(date)"
          sleep 1
        done
